[theme]
base="dark"

primaryColor="#1E88E5"        # Biru tua (button, highlight)
backgroundColor="#0B132B"     # Biru tua gelap (background utama)
secondaryBackgroundColor="#1C2541"  # Biru keabu (sidebar/card)
textColor="#FFFFFF"           # Putih
font="sans serif"
