[theme]
base="light"

primaryColor="#1E88E5"            # Biru utama
backgroundColor="#FFFFFF"         # Putih
secondaryBackgroundColor="#F1F5F9" # Abu-biru lembut
textColor="#0F172A"               # Biru gelap (nyaman dibaca)

font="sans serif"
